/**
 * @file part1.cpp
 * @brief Door Password Generation via MD5 Hashing
 *
 * This program computes the eight-character password required to unlock
 * a security door designed by the Easter Bunny engineers. The password
 * is generated by repeatedly hashing the Door ID (from the puzzle input)
 * concatenated with an increasing integer index, starting at 0.
 *
 * A valid character is found when the produced MD5 hash begins with
 * **five leading zeroes** in its hexadecimal representation. When this
 * occurs, the **sixth character** of the hash becomes the next character
 * of the password.
 *
 * This process continues until all eight characters of the password
 * have been discovered.
 *
 * Example:
 * - Door ID: "abc"
 *   - Index 3231929 → hash starts with "00000", sixth character is '1'
 *   - Index 5017308 → next character is '8'
 *   - Index 5278568 → next character is 'f'
 *   - Final password (after 8 such matches): 18f47a30
 *
 * The program performs this hashing search and outputs the final
 * eight-character password for the given Door ID.
 *
 * Puzzle Answer: [Password]
 *
 * @author [gabrielzschmitz]
 * @date [26/11/2025]
 */
#include <fstream>
#include <iomanip>
#include <iostream>
#include <openssl/md5.h>
#include <sstream>
#include <string>

bool debug = false;

void checkDebugFlag(const std::string &input, bool &debug) {
  size_t pos = input.find_last_of('/');

  std::string last_part =
      (pos == std::string::npos) ? input : input.substr(pos + 1);

  if (last_part == "test")
    debug = true;
}

std::string md5Hex(const std::string &input) {
  unsigned char digest[MD5_DIGEST_LENGTH];
  MD5((const unsigned char *)input.c_str(), input.length(), digest);

  std::stringstream ss;
  for (int i = 0; i < MD5_DIGEST_LENGTH; i++) {
    ss << std::hex << std::setw(2) << std::setfill('0') << (int)digest[i];
  }
  return ss.str();
}

int main(int argc, char *argv[]) {
  std::string user_input = (argc == 2) ? argv[1] : "input";
  checkDebugFlag(user_input, debug);

  std::ifstream input_file(user_input);
  if (!input_file.is_open()) {
    std::cerr << "FILE " << user_input << " UNAVAILABLE!" << std::endl;
    return 1;
  }

  std::string door_id;
  if (!std::getline(input_file, door_id)) {
    std::cerr << "Failed to read Door ID from input file." << std::endl;
    return 1;
  }

  std::string password;
  int index = 0;

  while ((int)password.size() < 8) {
    std::string to_hash = door_id + std::to_string(index);
    std::string hash = md5Hex(to_hash);

    if (hash.substr(0, 5) == "00000") {
      password += hash[5];
      if (debug)
        std::cout << "Found char " << hash[5] << " at index " << index
                  << " hash: " << hash << std::endl;
    }
    index++;
  }

  std::cout << "ANSWER: " << password << std::endl;

  return 0;
}
